Backlog/framework loader henrik
ftrackhq/integrations pull request #530
Opened 2024-06-11 13:40 UTC by henriknorin-ftrack

Resolves : 

* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-

- [ ] I have added automatic tests where applicable.
- [ ] The PR contains a description of what has been changed.
- [ ] The description contains manual test instructions.
- [ ] The PR contains update to the release notes.
- [ ] The PR contains update to the documentation.

This PR has been tested on :

- [ ] Windows.
- [ ] MacOs.
- [ ] Linux.

## Changes

## Test

2024-06-12 10:32 UTC, lluisFtrack requested changes

2024-06-12 10:32 UTC, lluisFtrack commented on projects/framework-nuke/extensions/nuke.yaml
> +      #      entity_type: component
```suggestion
```

2024-06-12 10:32 UTC, lluisFtrack commented on projects/framework-nuke/extensions/tool-configs/nuke-image-loader.yaml
> +    - ".tx"
Replace it by compatible....

2024-06-12 10:32 UTC, lluisFtrack commented on projects/framework-nuke/source/ftrack_framework_nuke/__init__.py
> +        )
Will improve this with the separated actions, and run_tool. But that will happen on the base branch.

2024-06-17 08:18 UTC, lluisFtrack requested changes

2024-06-17 08:55 UTC, lluisFtrack requested changes

2024-06-17 08:55 UTC, lluisFtrack commented on projects/framework-nuke/extensions/tool-configs/nuke-image-loader.yaml
> +      name: "Nuke image loader"
Why are we passing name inside options? Is this really needed?
Can't you put logic inside the plugin or the widget to get the name instead?

2024-06-18 08:52 UTC, lluisFtrack approved these changes

2024-06-18 09:35 UTC, henriknorin-ftrack commented on projects/framework-common-extensions/dialogs/standard_loader_dialog.py
> +            context_plugin['options'].update(self.dialog_options)
Decided to improve the calls within resolve_entity_paths plugin instead

2024-06-18 09:36 UTC, lluisFtrack approved these changes
Will need to be tested on the final QA

2024-06-18 09:37 UTC, merged