feat: flame integration
ftrackhq/integrations pull request #569
Opened 2024-08-09 10:10 UTC by hdd

Flame integration, first iteration. 

* runs on tasks
* allows to publish reviewables and thumbnails

2024-10-09 10:01 UTC, lluisFtrack requested changes
Please check comments. Also remember to align with the main branch.

2024-10-09 10:01 UTC, lluisFtrack commented on projects/framework-flame/extensions/plugins/flame_thumbnail_exporter.py
Maybe is not possible or worth it, but I see there is a lot of common stuff between this plugin and the reviewable one, should they be the same and be driven by the options? Just a thought.

2024-10-10 09:20 UTC, hdd commented on projects/framework-flame/resource/bootstrap/init.py
> +def get_timeline_custom_ui_actions():
Yes, this is how flame works to init menus .

https://help.autodesk.com/view/FLAME/2023/ENU/?guid=Flame_API_Python_Hooks_Reference_html

2024-10-10 09:20 UTC, hdd commented on projects/framework-flame/extensions/plugins/flame_scene_opener.py
no opener, as there's no way to save a project (is a set of folders, not a file).
I'll cleanup

2024-10-10 09:21 UTC, hdd commented on projects/framework-flame/extensions/plugins/flame_thumbnail_exporter.py
> +            raise PluginExecutionError(message=error)
this is used.

2024-10-10 09:21 UTC, hdd commented on projects/framework-flame/extensions/plugins/flame_thumbnail_exporter.py
rather keep them separated for clarity

2024-10-10 09:34 UTC, hdd commented on projects/framework-flame/README.md
> +2. Create a Python 3.7 virtual environment. If you're using an Apple Silicon chip, follow the instructions in the [How to install compatible PySide2 on Silicon based Mac](../../README.md#how-to-insta
updated, thanks.

2024-10-15 12:39 UTC, hdd commented on projects/framework-flame/resource/bootstrap/init.py
> +#     return get_ftrack_menu()
ended up removing them.

2024-10-15 12:59 UTC, hdd commented
@lluisFtrack 
I'm aware the wiretap.py module is not currently used or sourced anywhere.
I'm happy to nuke it if you feel like but could be useful for the next iteration.
let me know.

2024-10-16 09:25 UTC, hdd commented on projects/framework-flame/extensions/plugins/flame_thumbnail_exporter.py
> +            raise PluginExecutionError(message=error)
realised now what you meant, I'll cleanup

2024-10-17 09:44 UTC, lluisFtrack commented
> @lluisFtrack I'm aware the wiretap.py module is not currently used or sourced anywhere. I'm happy to nuke it if you feel like but could be useful for the next iteration. let me know.

We are trying to not leave any not used code in the production releases. So I would say nuke it for now and in case is needed, add it in the next iteration.

2024-10-17 09:56 UTC, lluisFtrack submitted a review, later dismissed
Tested on Mac and works. I think we need documentation for this, at least to explain where the menu is.

I think we will need to check the run in main thread thing sooner than later.

For the rest, all looks good to me, I would remove the wiretap.py module tough before merging.

Cheers.

2024-10-17 10:11 UTC, lluisFtrack submitted a review, later dismissed

2024-10-17 10:16 UTC, lluisFtrack approved these changes

2024-10-17 10:16 UTC, merged